apiVersion: v1
kind: Service
metadata:
  name: kustomize-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kustomize-test
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kustomize-test
  name: kustomize-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustomize-test
  template:
    metadata:
      labels:
        app: kustomize-test
    spec:
      containers:
      - image: gcr.io/searce-sandbox/abc:5baa800
        name: kustomize-test
        ports:
        - containerPort: 80
