apiVersion: v1
data:
  password: dmFyTXlEQlBhc3M=
  rootpw: dmFyTXlSb290UGFzcw==
  user: dmFyTXlEQlVzZXI=
kind: Secret
metadata:
  labels:
    app: php-hello-world
    mukesh/example: lamp
  name: mysql-credentials
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: php-hello-world
    mukesh/example: lamp
  name: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: php-hello-world
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: php-hello-world
    mukesh/example: lamp
  name: web
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: php-hello-world
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: php-hello-world
    mukesh/example: lamp
  name: mysql
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: php-hello-world
  template:
    metadata:
      labels:
        app: php-hello-world
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rootpw
              name: mysql-credentials
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: mysql-credentials
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-credentials
        - name: MYSQL_DATABASE
          value: sakila
        image: mysql:5.7
        livenessProbe:
          tcpSocket:
            port: 3306
        name: mysql
        ports:
        - containerPort: 3306
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: database
          subPath: data
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: database
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.php-dbconnect: glob:*
  labels:
    app: php-hello-world
    mukesh/example: lamp
  name: php-dbconnect
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: php-hello-world
  template:
    metadata:
      labels:
        app: php-hello-world
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: mysql-credentials
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-credentials
        - name: MYSQL_HOST
          value: mysql.default.svc.cluster.local
        image: mukeshpanigrahi/hello-world-repo
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 80
        name: php-dbconnect
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: php-hello-world
    mukesh/example: lamp
  name: mysql-data-loader-with-timeout
spec:
  activeDeadlineSeconds: 100
  template:
    metadata:
      labels:
        app: php-hello-world
      name: mysql-data-loader
    spec:
      containers:
      - command:
        - /tmp/mysql-sakila-data-loader.sh
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: mysql-credentials
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-credentials
        - name: MYSQL_HOST
          value: mysql.default.svc.cluster.local
        image: mukeshpanigrahi/hello-world-repo
        name: mysql-data-loader
      restartPolicy: OnFailure
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
  labels:
    app: php-hello-world
    mukesh/example: lamp
  name: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
